### Healthcheck
GET http://localhost:3000/api/health

### Listar entrenamientos
GET http://localhost:3000/api/entrenamientos?limit=20&offset=0

### Crear entrenamiento
POST http://localhost:3000/api/entrenamientos
Content-Type: application/json

{
  "fecha": "2026-07-16",
  "tipo": "Running",
  "distancia_km": 10,
  "duracion": "00:55:30",
  "intensidad": "Media",
  "sentimiento": "Con energía",
  "descripcion": "Fondo progresivo",
  "ciclo_menstrual": "Folicular",
  "alimentacion_previa": "Banana y agua"
}

### Obtener por ID
GET http://localhost:3000/api/entrenamientos/1

### Actualizar por ID
PUT http://localhost:3000/api/entrenamientos/1
Content-Type: application/json

{
  "intensidad": "Alta",
  "descripcion": "Registro actualizado desde REST Client"
}

### Eliminar por ID
DELETE http://localhost:3000/api/entrenamientos/1
